### ISSUE TITLE
Where are the PowerShell implementations?

### ISSUE THREAD

**Issue by juanchristian** [sensepost/DET#14]
Looking at the README I found the following code:

```
And in PowerShell (HTTP module):

PS C:\Users\user01\Desktop>
PS C:\Users\user01\Desktop> . .\http_exfil.ps1
PS C:\Users\user01\Desktop> HTTP-exfil 'C:\path\to\file.exe'

 PowerShell implementation (HTTP, DNS, ICMP, SMTP (used with Gmail))
```
But I can't find any **ps1** file in the project files, only **py** files.

**Comment by PaulSec** [comment]
Hello Juan, 

There were in the initial release but got dropped by some ex-colleagues because they did not implement AES encryption. 
I am working on getting them back in the new release I am doing for Black Hat EU (Arsenal). 

I will let you know as soon as I have the versions working.

**Comment by juanchristian** [comment]
@PaulSec thanks for the info.
