### ISSUE TITLE
License desagree DFSG

### ISSUE THREAD

**Issue by kretcheu** [sensepost/DET#4]
I'm a DM (Debian Maintainer) and I would like to put DET on Debain, but It can't go to main Debian because unfortunately The License Attribution-NonCommercial-ShareAlike 4.0 International disagree wirh Debian DFSG [1], and FSF Free Software Licenses. [2]

[1] https://wiki.debian.org/DFSGLicenses
[2] http://www.gnu.org/licenses/license-list.en.html?#CC-BY-NC

**Comment by PaulSec** [comment]
Hi there,

First of all, thanks a lot for your interest and willing to put DET on Debian. 
Let me check what I can do regarding the license and will get back to you as soon as possible.

**Comment by PaulSec** [comment]
Hi there, 

I am really sorry for the wait but we finally changed the license to MIT and this will now solve the problem. 
Let me know when DET lands on Debian or if you need any help :+1:

I will close the issue now.
