### ISSUE TITLE
Error installing DET Ubuntu 10.04

### ISSUE THREAD

**Issue by leacyber** [sensepost/DET#5]
Hi, first of all my english isn't good enough, so sorry about that. I'm trying to install DET on a Ubuntu 10.04 / 2.6.32-28-generic, and runs python 2.6.5.
When I run `pip install -r requirements.txt --user` I get the following error.
![captura](https://cloud.githubusercontent.com/assets/18465597/15576794/813d4e1e-2351-11e6-82bd-006be2adf8c2.PNG)

Should I update python version?. I'm new in this... Thanks.

**Comment by PaulSec** [comment]
Remove scapy from the requirements.txt and run `pip install -r requirements.txt --user`. 

Cheers.

**Comment by leacyber** [comment]
Thanks for the repply but I got exactly the same error. I think the problem is python's setuptools packet.

**Comment by PaulSec** [comment]
Mmh, yes, this might come for the setuptools. 
It works perfectly on Kali (latest) 

Do you have another box you can test it on?

**Comment by leacyber** [comment]
Yes, I installed it on kali 2.0, and ubuntu server 16.04 and works perfectly. I Would like to install on ubuntu 10 becouse it's the SO of a smart mirror.

**Comment by PaulSec** [comment]
I double checked the error message and it seems coming from a module called extern which is missing. 
Just used Google and I found [this thread](http://stackoverflow.com/questions/35446765/importerror-no-module-named-extern) 
Feel free to check this out, that might solve your issue.  

Glad you managed to install it perfectly on Kali 2.0 and Ubuntu Server 16.04. 

Cheers,

**Comment by leacyber** [comment]
I finally solved. I didn't realize that in /etc/apt/source.list was added kali repositories (I don't know why). I commented it and now it runs perfectly. Thanks!

**Comment by PaulSec** [comment]
Ah awesome, I am glad it works good for you now!

Best,
